### PR TITLE
Fix TextureBrush metafile handling

### LINKED ISSUE #331: Texture brush should support metafiles by converting them into a thumbnail
Currently returns NotImplemented

### LINKED ISSUE #332: Texture Brush ignores the image attributes wrap mode
Always WrapModeClamp

### PR DESCRIPTION
**Pull request by hughbe**
Fixes #332
Fixes #331

### CODE REVIEW

File: src/texturebrush.c [hunk 1]
```diff
@@ -770,7 +785,7 @@ GdipCreateTextureIAI (GpImage *image, GpImageAttributes *imageAttributes, int x,
 {
 	/* FIXME MonoTODO: Make use of ImageAttributes parameter when
 	 * ImageAttributes is implemented */
```
Comment (filipnavara) [inline src/texturebrush.c]: Is this FIXME still relevant?

Comment (hughbe) [reply src/texturebrush.c]: Yeah we still need to apply the image attributes to the image (e.g. recoloring)
