### PR TITLE
Add graphics clip tests and fix region bugs

### LINKED ISSUE #305: GdipGetClipBoundsI ignores the world transform matrix
```cpp
static void test_getClipBoundsI ()
{
	GpStatus status;
	GpImage *image;
	GpGraphics *graphics;
	GpRect bounds;

	graphics = getImageGraphics (&image);

	// Custom clip - transformed.
	GdipSetClipRect (graphics, 10, 20, 30, 40, CombineModeReplace);
	GdipTranslateWorldTransform (graphics, -10, -20, MatrixOrderAppend);

	status = GdipGetClipBoundsI (graphics, &bounds);
	assertEqualInt (status, Ok);
#if defined(USE_WINDOWS_GDIPLUS)
	assertEqualInt (bounds.X, 20);
	assertEqualInt (bounds.Y, 40);
	assertEqualInt (bounds.Width, 30);
	assertEqualInt (bounds.Height, 40);
#endif

	GdipDeleteGraphics (graphics);
}
```

### LINKED ISSUE #306: GdipGetVisibleClipBounds for image is empty but should be image bounds
```cpp
static void test_getVisibleClipBounds ()
{
	GpStatus status;
	GpImage *image;
	GpGraphics *graphics;
	GpRectF bounds;

	graphics = getImageGraphics (&image);
	
	// Default clip.
	status = GdipGetVisibleClipBounds (graphics, &bounds);
	assertEqualInt (status, Ok);
        // FIXME: this is incorrect in libgdiplus.
#if defined(USE_WINDOWS_GDIPLUS)
	assertEqualFloat (bounds.X, 0);
	assertEqualFloat (bounds.Y, 0);
	assertEqualFloat (bounds.Width, 100);
	assertEqualFloat (bounds.Height, 68);
#endif
}
```

### LINKED ISSUE #307: GdipIsVisibleClipEmpty ignores the set clip and only bases itself on the bounds
```cpp
static void test_isVisibleClipEmpty ()
{
	GpStatus status;
	GpImage *image;
	GpGraphics *graphics;
	BOOL isEmpty;

	graphics = getImageGraphics (&image);

	// Empty clip - no transform.
	GdipSetClipRect (graphics, 0, 0, 0, 0, CombineModeReplace);

	status = GdipIsVisibleClipEmpty (graphics, &isEmpty);
	assertEqualInt (status, Ok);
        // FIXME: this is incorrect in libgdiplus.
#if defined(USE_WINDOWS_GDIPLUS)
	assertEqualInt (isEmpty, TRUE);
#endif

	// Empty width clip - no transform.
	GdipSetClipRect (graphics, 10, 20, 0, 40, CombineModeReplace);

	status = GdipIsVisibleClipEmpty (graphics, &isEmpty);
	assertEqualInt (status, Ok);
        // FIXME: this is incorrect in libgdiplus.
#if defined(USE_WINDOWS_GDIPLUS)
	assertEqualInt (isEmpty, TRUE);
#endif

	// Empty height clip - no transform.
	GdipSetClipRect (graphics, 10, 20, 30, 0, CombineModeReplace);

	status = GdipIsVisibleClipEmpty (graphics, &isEmpty);
	assertEqualInt (status, Ok);
        // FIXME: this is incorrect in libgdiplus.
#if defined(USE_WINDOWS_GDIPLUS)
	assertEqualInt (isEmpty, TRUE);
#endif

	// Empty clip - transformed.
	GdipSetClipRect (graphics, 0, 0, 0, 0, CombineModeReplace);
	GdipTranslateWorldTransform (graphics, -10, -20, MatrixOrderAppend);

	status = GdipIsVisibleClipEmpty (graphics, &isEmpty);
	assertEqualInt (status, Ok);
        // FIXME: this is incorrect in libgdiplus.
#if defined(USE_WINDOWS_GDIPLUS)
	assertEqualInt (isEmpty, TRUE);
#endif

	GdipDeleteGraphics (graphics);	
}
```

### LINKED ISSUE #308: GdipSetClipGraphics ignores the source graphics transform
```cpp

static void test_setClipGraphics ()
{
	GpStatus status;
	GpImage *image;
	GpGraphics *graphics;
	GpGraphics *otherGraphics;
	GpRectF bounds;

	graphics = getImageGraphics (&image);
	otherGraphics = getImageGraphics (&image);

	// No transform.
	GdipSetClipRect (otherGraphics, 10, 20, 30, 40, CombineModeReplace);

	// Graphics transformed.
	GdipTranslateWorldTransform (graphics, -10, -20, MatrixOrderAppend);

	status = GdipSetClipGraphics (graphics, otherGraphics, CombineModeReplace);
	assertEqualInt (status, Ok);

	status = GdipGetClipBounds (graphics, &bounds);
	assertEqualInt (status, Ok);
#if defined(USE_WINDOWS_GDIPLUS)
	assertEqualFloat (bounds.X, 20);
	assertEqualFloat (bounds.Y, 40);
	assertEqualFloat (bounds.Width, 30);
	assertEqualFloat (bounds.Height, 40);
#endif

	GdipDeleteGraphics (graphics);
	GdipDeleteGraphics (otherGraphics);
}
```

### PR DESCRIPTION
**Pull request by hughbe**
Fixes #305
Fixes #306
Fixes #307 
Fixes #308

### CODE REVIEW

File: src/graphics.c [hunk 1]
```diff
@@ -558,12 +558,46 @@ GdipSaveGraphics (GpGraphics *graphics, unsigned int *state)
...
+}
+
 GpStatus WINGDIPAPI
 GdipResetWorldTransform (GpGraphics *graphics)
 {
 	if (!graphics)
 		return InvalidParameter;
 
+	GdipInvertMatrix (graphics->clip_matrix);
+	apply_world_to_bounds (graphics);
```
Comment (hughbe) [inline src/graphics.c]: The problem here was that each time the clip matrix is updated we use the transform to update the bounds. However, we never did this when calling GdipResetWorldTransform, so the old previously transformed bounds remained.

We need to invert the matrix as we're essentially undoing the previous transformation
